#!/usr/bin/env bash
#Check if all required parameters are provided

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Disable strict host key checking and transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check the exit status of scp command
if [ $? -eq 0 ]; then
    echo "File transfer successful!"
else
    echo "File transfer failed!"
fi

