#!/usr/bin/env bash
#script that prints the word best school 10 times but hi if 9

i=1

while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
